### PR TITLE
Added Custom Colors WOO!

### PR DESCRIPTION
**Pull request by aschmitigal22**
With an all new custom theme with custom color pickers you can now pick custom colors.

### CODE REVIEW

**Comment by aschmitigal22** [comment]
Now with custom names YAY

**Comment by aschmitigal22** [comment]
Now with QR function on the custom colors part YAYx2

**Review by awesomehaze — CHANGES_REQUESTED** [review]
Ok, these are some interesting changes. Firstly, there a bunch of errors and warnings when I build. Let's clean those up before releasing this. Next, I think the way the name changing is implemented is interesting... I don't know about the button on the home page, but it seems fine. I'd like it if you could edit all of the names at once instead on the bell schedule tab, that way there is much less clutter. We should probably add tooltips or something to let users know what the heck the buttons are for.

The source code link on the about page is a good idea too, but the formatting is a bit off. We should make it seem like more natural language instead of "source code can be found at" and then a new line.

Let me know if you have any questions about anything, I'm happy to help with code or anything else.

**Comment by aschmitigal22** [comment]
Yes, I agree with everything you said. For the homepage icons, we could remove the reset icon to make it just the edit one to shrink the box a bit. Also, the name-changing icons on the bell schedule page could pop up with a toggle or show up on hover instead of being there by default.

I will need help with fixing the JS errors because I don't know JS very well and help with making it use v-for and things like that to remove the DOM editing.

So here is a somewhat complete TODO:
- [ ] Fix JS compile errors
- [ ] Optimize code to use Vue functions (v-for) - remove DOM edits
- [ ] Declutter the bell schedule page and move the name change icons
- [ ] Change Source Code link to be more readable
- [ ] Add tooltips to the icons

**Comment by awesomehaze** [comment]
Great, I'll take a look at the code to work on the errors when I have some time. Thanks for taking initiative with all this!

**Pull request closed without merging**
